# Hardware configuration for renderer
# Originally generated by 'nixos-generate-config'
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "thunderbolt"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1c612945-3ff3-410d-b173-deb84d107c6d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0c97c018-3ee2-4ea6-82d8-7e86e679ef4c".device =
    "/dev/disk/by-uuid/0c97c018-3ee2-4ea6-82d8-7e86e679ef4c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0228-ADC5";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home/json/3d-mount" = {
    device = "/dev/disk/by-uuid/CEE65294E6527D21";
    fsType = "ntfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6f111701-209a-41f8-b399-50aecfec91c9"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
